export enum NotificationType {
    PERMISSION_REQUEST = 'PERMISSION_REQUEST',
    PERMISSION_APPROVED = 'PERMISSION_APPROVED',
    PERMISSION_REJECTED = 'PERMISSION_REJECTED',
    DOCUMENT_UPDATE = 'DOCUMENT_UPDATE',
    DOCUMENT_DELETED = 'DOCUMENT_DELETED',
}
